- src/chainsync/chainsync.service.ts
- src/config/network.ts
- src/lib/chain/index.ts
> feat: 🎸 sync chain info

- .github/workflows/deploy.yml
- Dockerfile
> ci: 🎡 cd:continuous-deployment

- .github/workflows/deploy.yml
> fix: 🐛 Deployment failed multiple times

- src/app.module.ts
- src/version/version.controller.ts
- src/version/version.service.ts
- test/app.e2e-spec.ts
> feat: 🎸 support version

- src/backgroundTask/context/index.ts
- src/backgroundTask/decoder/index.ts
- src/backgroundTask/interface/index.ts
- src/config/backgroundTask.ts
- src/config/evm.ts
> feat: 🎸 complete evmcontext

- .github/workflows/deploy.yml
> fix: 🐛 confirm whether it is running normally

- package-lock.json
- package.json
- src/app.module.ts
- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/index.ts
- src/car/car.controller.ts
- src/car/car.service.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 Add car API and test code

- src/app.module.ts
- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/index.ts
- src/datasetRequirement/datasetRequirement.controller.ts
- src/datasetRequirement/datasetRequirement.service.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 Add datasetRequirement api and test code

- src/app.module.ts
- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/index.ts
- src/datasetProofMetadata/datasetProofMetadata.controller.ts
- src/datasetProofMetadata/datasetProofMetadata.service.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 Add datasetProofMetadata API and test code

- .vscode/launch.json
- src/app.module.ts
- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/index.ts
- src/matchingMetadata/matchingMetadata.controller.ts
- src/matchingMetadata/matchingMetadata.service.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 Add matchingMetadata API and test code

- Dockerfile
> fix: 🐛 Dockerfile adds code build

- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/index.ts
> fix: 🐛 Resolve code conflicts

- src/app.module.ts
- src/matchingTarget/matchingTarget.controller.ts
- src/matchingTarget/matchingTarget.service.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 Add matchingTarget API and test code

- src/car/car.controller.ts
- src/car/car.service.ts
- src/carReplica/carReplica.controller.ts
- src/carReplica/carReplica.service.ts
> fix: 🐛 Add car and carReplica add total interface

- package-lock.json
- package.json
> fix: 🐛 update dataswapjs to 0.13.2

- package-lock.json
- package.json
- src/backgroundTask/storager/index.ts
> feat: 🎸 update dataswapjs version to 0.16.1

- src/backgroundTask/storager/index.ts
> feat: 🎸 update the 'size','requirement' in MatchingMetadata

- package-lock.json
- package.json
> feat: 🎸 update dataswapjs version to 0.17.0

- src/backgroundTask/interface/config.ts
- src/backgroundTask/storager/index.ts
> feat: 🎸 Update bid and funds in MatchingMetadata

- src/backgroundTask/storager/index.ts
> feat: 🎸 process update the 'status' field in DatasetMetadata

- src/backgroundTask/interface/config.ts
- src/backgroundTask/storager/index.ts
> feat: 🎸 process update the 'status' field in MatchingMetadata

- package-lock.json
- package.json
> feat: 🎸 update dataswapjs version to 0.17.1

- src/backgroundTask/storager/index.ts
> feat: 🎸 update the 'replicaInfos' field in Car model

- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/index.ts
- src/backgroundTask/storager/index.ts
> feat: 🎸 Add store MatchingBids model

- src/backgroundTask/interface/config.ts
- src/backgroundTask/storager/index.ts
> feat: 🎸 update the 'state' field in CarReplica model

- src/backgroundTask/interface/config.ts
- src/backgroundTask/storager/index.ts
> feat: 🎸 update the matchings field in DatasetRequirment

- src/app.module.ts
- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/index.ts
- src/backgroundTask/storager/index.ts
- src/matchingBids/matchingBids.controller.ts
- src/matchingBids/matchingBids.service.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> fix: 🐛 Add store MatchingBids API and test

- src/backgroundTask/storager/index.ts
> feat: 🎸 Complete the DatasetId for Matching-related methods

- package-lock.json
- package.json
> feat: 🎸 update dataswapjs version to 0.17.2

- package-lock.json
- package.json
> fix: 🐛 update dataswapjs version to 0.17.4

- package-lock.json
- package.json
- src/backgroundTask/interface/config.ts
- src/backgroundTask/storager/index.ts
> feat: 🎸 update Dataset Size into the dataset proof

- package-lock.json
- package.json
> fix: 🐛 update dataswapjs version to 0.18.2

- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/config.ts
- src/backgroundTask/interface/index.ts
- src/backgroundTask/storager/index.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 Add datastore of the datasetchalange

- src/app.module.ts
- src/datasetChallenge/datasetChallenge.controller.ts
- src/datasetChallenge/datasetChallenge.service.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
> feat: 🎸 add api of datasetchallenge

- src/backgroundTask/storager/index.ts
> fix: 🐛 update the winner in matchingmetadata

- src/backgroundTask/storager/index.ts
> fix: 🐛 fix params of closeMatching

- package-lock.json
- package.json
- src/backgroundTask/context/index.ts
- src/backgroundTask/decoder/index.ts
- src/backgroundTask/interface/index.ts
- src/config/backgroundTask.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 update dataswapjs version to 0.22.0

- package-lock.json
- package.json
- src/backgroundTask/context/index.ts
- src/backgroundTask/decoder/index.ts
- src/backgroundTask/interface/index.ts
- src/config/backgroundTask.ts
> feat: 🎸 Replace escrow to finance contract

- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/config.ts
- src/backgroundTask/interface/index.ts
- src/backgroundTask/storager/index.ts
> feat: 🎸 Collection and storage of members statistical

- src/api/datasetsBasicStatistics/datasetsBasicStatistics.controller.ts
- src/api/datasetsBasicStatistics/datasetsBasicStatistics.service.ts
- src/app.module.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 Implementation of APIs related to Datasets statistics

- src/backgroundTask/context/index.ts
- src/backgroundTask/interface/config.ts
- src/backgroundTask/interface/index.ts
- src/backgroundTask/storager/index.ts
> feat: 🎸 Collection and storage of Storages statistical

- src/api/member/member.controller.ts
- src/api/member/member.service.ts
- src/app.module.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> feat: 🎸 Implementation of APIs related to Member statistics

- package-lock.json
- package.json
- src/backgroundTask/storager/index.ts
> feat: 🎸 update dataswapjs version to 0.23.0

- package-lock.json
- package.json
- src/backgroundTask/storager/index.ts
> feat: 🎸 update dataswapjs version to 0.23.1

- package-lock.json
- package.json
- src/api/statistics/datasetsStatistics.controller.ts
- src/api/statistics/datasetsStatistics.service.ts
- src/api/statistics/matchingsStatistics.controller.ts
- src/api/statistics/matchingsStatistics.service.ts
- src/api/statistics/storagesStatistics.controller.ts
- src/api/statistics/storagesStatistics.service.ts
- src/app.module.ts
- src/backgroundTask/context/index.ts
- src/backgroundTask/decoder/index.ts
- src/backgroundTask/index.ts
- src/backgroundTask/interface/index.ts
- src/backgroundTask/storager/index.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/backgroundTask/index.spec.ts
> fix: 🐛 Revise inappropriate naming conventions for statistical

- src/backgroundTask/context/index.ts
- src/backgroundTask/index.ts
- src/backgroundTask/interface/index.ts
- src/config/backgroundTask.ts
> fix: 🐛 Synchronize with a confidence of 6 blocks

- package-lock.json
- package.json
> fix: 🐛 update dataswawpjs version to 0.25.6

- package-lock.json
- package.json
> fix: 🐛 update dataswapjs version to 0.25.7
